export const FAQ_ITEMS = [
  { q: 'Intervenez-vous pour des mariages en Pays de la Loire ?',
    a: "Oui. Basé à Nort-sur-Erdre, Myracoustic intervient principalement en Pays de la Loire — Nantes, Angers, Rennes, Saint-Nazaire et leurs environs. Des interventions en dehors de la région peuvent être étudiées selon la nature du projet." },
  { q: 'Gérez-vous la musique de la cérémonie laïque ?',
    a: "Oui. Nous pouvons sonoriser votre cérémonie laïque (ou religieuse si l'acoustique le nécessite) : micro sans fil pour l'officiant, musique d'entrée et de sortie personnalisée, lectures amplifiées. C'est un moment clé que nous préparons avec vous bien en amont." },
  { q: 'Peut-on choisir la playlist musicale pour notre mariage ?',
    a: "Absolument. Nous construisons ensemble la playlist : morceaux incontournables, styles à privilégier ou à éviter, genres à éviter par génération d'invités. L'ouverture de bal est préparée et répétée. Le DJ s'adapte ensuite en temps réel à l'ambiance de la piste." },
  { q: 'Proposez-vous une animation avec micro pour les discours et animations ?',
    a: "Oui. Nous fournissons des micros sans fil pour les discours, l'ouverture de bal, le lancer de bouquet et toutes les prises de parole. L'animation au micro reste discrète et élégante, centrée sur vos invités et vos choix." },
  { q: 'Quel est le délai pour réserver votre prestation mariage ?',
    a: "Nous recommandons de nous contacter le plus tôt possible, idéalement 6 à 12 mois à l'avance pour un mariage, afin de garantir notre disponibilité à votre date. N'hésitez pas à nous contacter même pour une date proche — nous faisons notre possible." },
  { q: "Travaillez-vous avec des wedding planners et d'autres prestataires ?",
    a: "Oui. Nous coordonnons régulièrement avec des wedding planners, traiteurs, photographes et vidéastes. Une bonne communication entre prestataires est essentielle pour que chaque moment se déroule sans accroc." },
  { q: 'Faut-il prévoir un repas pour le DJ ?',
    a: "Oui, il est d'usage de prévoir un repas pour le DJ (et le technicien selon la configuration), idéalement décalé pour maintenir une présence technique constante. Ce point est précisé dans notre devis et nos CGV." },
  { q: 'Peut-on faire appel à vous uniquement pour la sonorisation de cérémonie, sans DJ ?',
    a: "Oui. Nos prestations sont modulables. Vous pouvez nous confier uniquement la sonorisation de la cérémonie ou du cocktail, sans animation DJ pour la soirée — ou opter pour une formule complète de la cérémonie aux dernières danses." },
  { q: 'Comment se passe le paiement ?',
    a: "Un acompte est demandé à la réservation pour bloquer votre date. Le solde est réglé avant ou le jour de l'événement selon les modalités du devis. Toutes les conditions sont précisées dans notre contrat et nos CGV." },
  { q: "Que se passe-t-il en cas d'imprévu technique le jour J ?",
    a: "Nous anticipons les imprévus en testant tout le matériel avant l'arrivée de vos invités et en ayant du matériel de secours. Notre expérience nous permet de gérer les aléas rapidement et discrètement, sans jamais perturber le déroulement de votre soirée." },
];
